feat(ci): run UI e2e tests
Signed-off-by: Michael Crenshaw <350466+crenshaw-dev@users.noreply.github.com>

diff --git a/ui-test/Dockerfile b/ui-test/Dockerfile
--- a/ui-test/Dockerfile
+++ b/ui-test/Dockerfile
@@ -3,16 +3,17 @@ FROM docker.io/library/node:22.9.0@sha256:cbe2d5f94110cea9817dd8c5809d05df49b4bd
 RUN apt-get update && apt-get install --no-install-recommends -y \
     software-properties-common 
 
-#Chrome browser to run the tests
+# Chrome browser to run the tests
 ARG CHROME_VERSION=86.0.4240.75
+# TODO: use something besides the deprecated `apt-key add`.
 RUN curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add \
     && wget https://www.slimjet.com/chrome/download-chrome.php?file=files%2F$CHROME_VERSION%2Fgoogle-chrome-stable_current_amd64.deb \
-    && dpkg -i download-chrome*.deb || true
+    && dpkg -i download-chrome*.deb || true # ignore error because it's probably for missing dependencies
 
 RUN apt-get install --no-install-recommends -y -f \
     && rm -rf /var/lib/apt/lists/*
 
-#Disable the SUID sandbox so that chrome can launch without being in a privileged container
+# Disable the SUID sandbox so that chrome can launch without being in a privileged container
 RUN dpkg-divert --add --rename --divert /opt/google/chrome/google-chrome.real /opt/google/chrome/google-chrome \
     && echo "#! /bin/bash\nexec /opt/google/chrome/google-chrome.real --no-sandbox --disable-setuid-sandbox \"\$@\"" > /opt/google/chrome/google-chrome \
      && chmod 755 /opt/google/chrome/google-chrome
@@ -22,4 +23,3 @@ COPY package*.json ./
 COPY yarn.lock ./
 RUN yarn install && yarn cache clean
 COPY . .
-
