do things faster
Signed-off-by: Michael Crenshaw <350466+crenshaw-dev@users.noreply.github.com>

diff --git a/.github/workflows/ci-build.yaml b/.github/workflows/ci-build.yaml
--- a/.github/workflows/ci-build.yaml
+++ b/.github/workflows/ci-build.yaml
@@ -499,25 +499,26 @@ jobs:
             fi
             count=$((count+1))
           done
-      - name: Run E2E testsuite
-        run: |
-          set -x
-          make test-e2e-local
-          goreman run stop-all || echo "goreman trouble"
-          sleep 30
-      - name: Upload e2e coverage report
-        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
-        with:
-          name: e2e-code-coverage
-          path: /tmp/coverage
-        if: ${{ matrix.k3s.latest }}
-      - name: Upload e2e-server logs
-        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
-        with:
-          name: e2e-server-k8s${{ matrix.k3s.version }}.log
-          path: /tmp/e2e-server.log
-        if: ${{ failure() }}
+#      - name: Run E2E testsuite
+#        run: |
+#          set -x
+#          make test-e2e-local
+#          goreman run stop-all || echo "goreman trouble"
+#          sleep 30
+#      - name: Upload e2e coverage report
+#        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
+#        with:
+#          name: e2e-code-coverage
+#          path: /tmp/coverage
+#        if: ${{ matrix.k3s.latest }}
+#      - name: Upload e2e-server logs
+#        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
+#        with:
+#          name: e2e-server-k8s${{ matrix.k3s.version }}.log
+#          path: /tmp/e2e-server.log
+#        if: ${{ failure() }}
       - name: Run UI e2e tests
+        if: ${{ matrix.k3s.latest }}  # Only bother running for the latest version.
         run: |
           yarn install --frozen-lockfile --ignore-optional --non-interactive
           yarn test
